# data initialization

batch_size: 128

# tool initialization

nb_classes: 10
input_size_classifier: 512

nb_cycles: 1
nb_epochs_self_supervised_by_cycle: 1
nb_epochs_supervised_by_cycle: 1

# hyperparameters for the model

criterion_ss:
  name: "NTXentLoss"

optimizer_ss:
  name: "SGD"
  params:
    lr: 0.3
    momentum: 0.9
    weight_decay: 0.000001

scheduler_ss:
  name: "CosineAnnealingLR"
  params:
    T_max: "$(nb_cycles * nb_epochs_self_supervised_by_cycle)"
    eta_min: 0

criterion_su:
  name: "CrossEntropyLoss"

optimizer_su:
  name: "SGD"
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005

scheduler_su:
  name: "CosineAnnealingLR"
  params:
    T_max: "$(nb_cycles * nb_epochs_supervised_by_cycle)"
    eta_min: 0
